import type { Call, Reservation, HotelKnowledgeItem } from './types';
export const INITIAL_LIVE_CALL: Call = { id: 'CALL-2026-089', callerName: 'Sarah Johnson', callerPhone: '+234 801 492 8821', timestamp: 'Just now', duration: '02:41', intent: 'Room Amenities & Reservation Inquiry', status: 'IN_PROGRESS', humanEscalated: false, aiActions: ['Queried Knowledge: Air Conditioning Policy', 'Checked Room Availability: Oct 14 - Oct 17', 'Created Draft Reservation #RES-9042'], transcript: [{id:'m1',sender:'CALLER',text:'Do your rooms have air conditioning?',timestamp:'00:12'},{id:'m2',sender:'AVA',text:'Yes, all of our guest rooms are air-conditioned. The Deluxe rooms also have individual temperature controls.',timestamp:'00:18'},{id:'m3',sender:'CALLER',text:'Okay. I would like to book a room for next weekend.',timestamp:'00:45'},{id:'m4',sender:'AVA',text:'Absolutely. I can help with that. What dates would you like to stay?',timestamp:'00:52'}] };
export const MOCK_RESERVATIONS: Reservation[] = [
{id:'RES-9042',guestName:'Sarah Johnson',guestEmail:'s.johnson@example.com',roomType:'Deluxe King',checkIn:'Oct 14, 2026',checkOut:'Oct 17, 2026',guestsCount:2,totalAmountNaira:180000,status:'Awaiting confirmation',specialRequests:'High floor, late check-in around 9 PM',relatedCallId:'CALL-2026-089',aiActionsApplied:['Captured guest contact via Voice','Held room block for 2 hours','SMS payment link dispatched']},
{id:'RES-8821',guestName:'Michael James',guestEmail:'mjames@corp.ng',roomType:'Executive Room',checkIn:'Oct 05, 2026',checkOut:'Oct 07, 2026',guestsCount:2,totalAmountNaira:240000,status:'Confirmed',aiActionsApplied:['Confirmed payment','Scheduled driver transfer']},
{id:'RES-8700',guestName:'Dr. Amina Bello',guestEmail:'a.bello@lagoshealth.org',roomType:'Aurelia Suite',checkIn:'Oct 20, 2026',checkOut:'Oct 25, 2026',guestsCount:1,totalAmountNaira:750000,status:'Confirmed',aiActionsApplied:['Verified VIP guest protocol','Notified Front Desk Manager']}
];
export const MOCK_KNOWLEDGE: HotelKnowledgeItem[] = [
{id:'k1',title:'CASE-STUDY HOTEL PROFILE',category:'FAQs',content:'The Aurelia is a fictional boutique hotel concept on Victoria Island, Lagos. This knowledge set is sample demo content, not verified operating information.',lastUpdated:'Draft demo profile'},
{id:'k2',title:'ROOM TYPES & INDICATIVE RATES',category:'Rooms',content:'Illustrative case-study base rates per night: Deluxe King ₦60,000; Executive Room ₦120,000; Aurelia Suite ₦150,000. These sample rates are not live quotes. Taxes, service charges, dates, occupancy, and availability have not been verified; staff must confirm a final quote.',availableIn:['Deluxe King','Executive Room','Aurelia Suite'],lastUpdated:'Draft demo profile'},
{id:'k3',title:'IN-ROOM COMFORTS',category:'Rooms',content:'Demo assumption for this case study: all room types include air conditioning with individual controls, complimentary Wi-Fi, a Smart TV with common streaming apps (guests use their own accounts), a kettle, mini-fridge, in-room safe, and work desk. The Executive Room and Aurelia Suite also include a lounge area.',availableIn:['Deluxe King','Executive Room','Aurelia Suite'],lastUpdated:'Draft demo profile'},
{id:'k4',title:'CHECK-IN, CHECK-OUT & STAY POLICIES',category:'Policies',content:'Standard check-in is 3:00 PM and check-out is 11:00 AM. Early check-in and late check-out depend on availability and may have a fee; confirm with the front desk. Ask the hotel team to confirm cancellation, deposit, and visitor policies.',availableIn:['All Accommodations'],lastUpdated:'Draft demo profile'},
{id:'k5',title:'POOL, FITNESS & WELLNESS',category:'Amenities',content:'Demo assumptions: the outdoor pool is open daily 7:00 AM–9:00 PM for registered guests, weather and maintenance permitting. The fitness studio is open 24 hours with room-key access. The Aurelia Spa offers massage and facial appointments daily 10:00 AM–8:00 PM; treatment menu and pricing require staff confirmation.',lastUpdated:'Draft demo profile'},
{id:'k6',title:'THE SUNKEN LOUNGE & ROOM SERVICE',category:'Dining',content:'Breakfast is served daily 6:30 AM–10:30 AM. The Sunken Lounge restaurant serves lunch 12:00 PM–3:00 PM and dinner 6:00 PM–10:30 PM. In-room dining is available 24/7. Breakfast inclusion depends on the guest rate plan; check the reservation before promising it is included.',lastUpdated:'Draft demo profile'},
{id:'k7',title:'SAMPLE RESTAURANT MENU & PRICES',category:'Dining',content:'Illustrative demo menu only: Aurelia breakfast tray ₦18,000; Lagos jollof rice with grilled chicken ₦12,000; chicken suya bowl ₦16,000; grilled whole snapper ₦28,000; small-chops platter ₦10,000; seasonal fruit bowl ₦7,000. Prices are sample case-study amounts, not approved or current menu prices. Confirm availability, dietary needs, taxes, and final prices with the restaurant.',lastUpdated:'Draft demo profile'},
{id:'k8',title:'THE SAFFRON BAR & SAMPLE DRINKS',category:'Dining',content:'Demo assumption: The Saffron Bar is open daily 3:00 PM–12:00 AM. Illustrative drinks: chilled zobo ₦4,000; classic Chapman ₦5,000; fresh lime-and-ginger mocktail ₦6,000; house signature cocktail ₦9,000; Nigerian lager ₦5,000. These are sample prices only. Ask about current stock, non-alcoholic options, allergies, and final prices before confirming.',lastUpdated:'Draft demo profile'},
{id:'k9',title:'AIRPORT TRANSFERS',category:'Transportation',content:'A private SUV transfer from Murtala Muhammed International Airport is listed at an illustrative ₦45,000 per vehicle, one way. It must be requested in advance and confirmed by the transport team. Ask for arrival date, flight number, passenger count, and luggage count. Do not claim a vehicle is booked until staff confirms it.',lastUpdated:'Draft demo profile'},
{id:'k10',title:'LOCAL IDEAS AROUND LAGOS',category:'Location',content:'Possible outings to discuss with guests include Nike Art Gallery, Lekki Conservation Centre, beaches around Lekki, and dining or shopping on Victoria Island. Travel time, opening hours, admission, traffic, and safe transport arrangements change; verify with the hotel team before giving specifics. Ask what kind of outing the guest prefers.',lastUpdated:'Draft demo profile'},
{id:'k11',title:'HOW AVA SHOULD HANDLE QUESTIONS',category:'FAQs',content:'Answer warmly using the relevant facts in this draft demo catalogue. When asked about an unlisted detail, be transparent, offer a useful related option from the catalogue, and ask a natural follow-up question. Do not invent facilities, menu items, prices, opening hours, accessibility features, availability, or bookings. Clearly call sample prices indicative and have staff confirm them.',lastUpdated:'Draft demo profile'}
];
export const MOCK_CALL_HISTORY: Call[] = [
{id:'CALL-0942',callerName:'Sarah Johnson',callerPhone:'+234 801 XXX XXXX',timestamp:'09:42 AM',duration:'02:41',intent:'Booking request',status:'RESOLVED',humanEscalated:false,transcript:[],aiActions:['Checked Room Availability','Drafted Booking']},
{id:'CALL-0931',callerName:'David O. Adeleke',callerPhone:'+234 803 XXX XXXX',timestamp:'09:31 AM',duration:'01:15',intent:'Room inquiry',status:'RESOLVED',humanEscalated:false,transcript:[],aiActions:['Provided AC & WiFi Policy']},
{id:'CALL-0918',callerName:'Chief Kenneth Utomi',callerPhone:'+234 809 XXX XXXX',timestamp:'09:18 AM',duration:'03:02',intent:'Airport transfer',status:'HANDED_OFF',humanEscalated:true,transcript:[],aiActions:['Escalated to Front Desk Lead']}
];
